# NodePort 단점 보완
# 브라우저는 NodePort에 직접 요청을 보내는 것이 아니라
# Load Balancer에 요청한다.
# LB는 살아있는 노드로 요청이 가도록 한다.

apiVersion: v1
kind: Service
metadata:
  name: counter-lb
spec:
  type: LoadBalancer
  ports:
    - port: 30000
      targetPort: 3000
      protocol: TCP
  selector:
    app: counter
    tier: app
