# NodePort
# 외부(노드)에서 접근 가능
# 클러스터의 모든 노드에 포트 오픈.

apiVersion: v1
kind: Service
metadata:
  name: counter-np
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      # 노드에 오픈할 Port (미지정시 30000~32768 랜덤 할당)
      nodePort: 31000
