# 오브젝트 버전 v1, app/v1, networking.k8s.io/v1, ...
apiVersion: v1
# 종류 Pod, ReplicaSet, Deployment, Service, ...
kind: Pod
# 메타데이터 name과 label, annotation(주석)으로 구성
metadata:
  name: echo
  labels:
    app: echo
# 리소스 종류마다 다름
spec:
  containers:
    - name: app
      image: ghcr.io/subicura/echo:v1
      # 준비프로브 readinessProbe: 성공하면 pod이 준비된것으로 표시. 재시작하지 않고 요청 제외
      readinessProbe:
        httpGet:
          path: /not/exist
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 2 # Default 1
        periodSeconds: 5 # Defaults 10
        failureThreshold: 1 # Defaults 3
      resources:
        limits:
          memory: 512Mi
          cpu: '1'
        requests:
          memory: 256Mi
          cpu: '0.2'
