apiVersion: apps/v1
# label을 체크해서 원하는 수의 Pod이 없으면 새로운 Pod 생성
kind: ReplicaSet
metadata:
  name: echo-rs
spec:
  # 원하는 Pod의 개수
  replicas: 1
  # label 체크 조건
  selector:
    matchLabels:
      app: echo
      tier: app
  # 생성할 pod의 명세
  template:
    metadata:
      labels:
        app: echo
        tier: app
    spec:
      containers:
        - name: echo
          image: ghcr.io/subicura/echo:v1
